apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: clusterdeployments.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: ClusterDeployment
    plural: clusterdeployments
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              properties:
                admin:
                  properties:
                    email:
                      type: string
                    password:
                      type: object
                    sshKey:
                      type: object
                  required:
                  - email
                  - password
                  type: object
                baseDomain:
                  type: string
                clusterID:
                  type: string
                machines:
                  items:
                    properties:
                      name:
                        type: string
                      platform:
                        properties:
                          aws:
                            properties:
                              iamRoleName:
                                type: string
                              rootVolume:
                                properties:
                                  iops:
                                    format: int64
                                    type: integer
                                  size:
                                    format: int64
                                    type: integer
                                  type:
                                    type: string
                                required:
                                - iops
                                - size
                                - type
                                type: object
                              type:
                                type: string
                            required:
                            - type
                            - iamRoleName
                            - rootVolume
                            type: object
                          libvirt:
                            properties:
                              qcowImagePath:
                                type: string
                            required:
                            - qcowImagePath
                            type: object
                        type: object
                      replicas:
                        format: int64
                        type: integer
                    required:
                    - name
                    - replicas
                    - platform
                    type: object
                  type: array
                networking:
                  properties:
                    podCIDR:
                      type: string
                    serviceCIDR:
                      type: string
                    type:
                      type: string
                  required:
                  - type
                  - serviceCIDR
                  - podCIDR
                  type: object
                platform:
                  properties:
                    aws:
                      properties:
                        region:
                          type: string
                        tags:
                          type: object
                        vpcCIDRBlock:
                          type: string
                        vpcID:
                          type: string
                      required:
                      - region
                      - vpcID
                      - vpcCIDRBlock
                      type: object
                    libvirt:
                      properties:
                        URI:
                          type: string
                        masterIPs:
                          items:
                            format: byte
                            type: string
                          type: array
                        network:
                          properties:
                            if:
                              type: string
                            ipRange:
                              type: string
                            name:
                              type: string
                          required:
                          - name
                          - if
                          - ipRange
                          type: object
                      required:
                      - URI
                      - network
                      - masterIPs
                      type: object
                  type: object
                pullSecret:
                  type: object
              required:
              - clusterID
              - admin
              - baseDomain
              - networking
              - machines
              - platform
              - pullSecret
              type: object
            platformSecrets:
              properties:
                aws:
                  properties:
                    credentials:
                      type: object
                  required:
                  - credentials
                  type: object
              type: object
          required:
          - config
          - platformSecrets
          type: object
        status:
          properties:
            clusterUUID:
              type: string
            installed:
              type: boolean
          required:
          - installed
          - clusterUUID
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null