apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: dnszones.hive.openshift.io
spec:
  group: hive.openshift.io
  names:
    kind: DNSZone
    plural: dnszones
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            aws:
              properties:
                accountSecret:
                  type: object
                region:
                  type: string
              required:
              - accountSecret
              - region
              type: object
            zone:
              type: string
          required:
          - zone
          type: object
        status:
          properties:
            lastSyncGeneration:
              format: int64
              type: integer
            lastSyncTimestamp:
              format: date-time
              type: string
          required:
          - lastSyncGeneration
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []