apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-controller-manager
  namespace: openshift-hive
  labels:
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  replicas: 1
  revisionHistoryLimit: 4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      # By default we are assuming a development setup with the image pushed to
      # the local registry. Pull policy should be Never in this case, it will be
      # modified in overrides for actual environments.
      - image: hive-controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        command:
        - /opt/services/manager
        - --log-level
        - debug
      terminationGracePeriodSeconds: 10