apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hive-operator
  template:
    metadata:
      labels:
        name: hive-operator
    spec:
      serviceAccountName: hive-operator
      containers:
        - name: hive-operator
          # Replace this with the built image name
          image: quay.io/dgoodwin/hive:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - hive-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "hive-operator"
